name: Docker

on:
  push:
    branches:
      - 'latest'
      - '2.4.x'
      - '2.5.x'
  workflow_dispatch:

env:
  PLATFORMS: 'linux/amd64,linux/arm64,linux/i386,linux/armhf'
  TARGET_IMAGE: "${GITHUB_ACTOR}/urbackup-client"
  
jobs:
  environment-variables:
    runs-on: ubuntu-latest
    steps:
      - name: print default environment variables
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Set environmental variables"
        run: |
          echo "TARGET_IMAGE=${TARGET_IMAGE}" >> $GITHUB_ENV
          echo "PLATFORMS=${PLATFORMS}" >> $GITHUB_ENV

      -  
        name: Check value
        id: target
        run: |
          echo "${{ env.TARGET_IMAGE }}" 
          echo "${{ env.PLATFORMS }}" 
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          # images: ${{ env.GITHUB_ACTOR}}/${{ env.GITHUB_REF_NAME }}
          images:  "${{ env.TARGET_IMAGE }}"
          # generate Docker tags based on the following events/attributes
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${PLATFORMS}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
